# Generated by Django 4.2.4 on 2023-10-22 15:54

from django.db import migrations, models


def set_age_groups(apps, schema_editor):
    Person = apps.get_model('main_app', 'Person')
    for person in Person.objects.all():
        if person.age <= 12:
            person.age_group = 'Child'
        elif 13 <= person.age <= 17:
            person.age_group = 'Teen'
        else:
            person.age_group = 'Adult'
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.PositiveIntegerField()),
                ('age_group', models.CharField(default='No age group', max_length=20)),
            ],
        ),
        migrations.RunPython(set_age_groups),
    ]
