# Generated by Django 4.2.4 on 2023-10-22 16:06

from django.db import migrations, models


def set_item_rarity(apps, schema_editor):
    Item = apps.get_model('main_app', 'Item')
    for item in Item.objects.all():
        if item.price <= 10:
            item.rarity = 'Rare'
        elif 11 <= item.price <= 20:
            item.rarity = 'Very Rare'
        elif 21 <= item.price <= 30:
            item.rarity = 'Extremely Rare'
        else:
            item.rarity = 'Mega Rare'
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('rarity', models.CharField(default='empty', max_length=20)),
            ],
        ),
        migrations.RunPython(set_item_rarity),
    ]
