# Generated by Django 4.2.4 on 2023-10-22 16:12

from django.db import migrations, models


def set_new_price(apps, schema_editor):
    Smartphone = apps.get_model('main_app', 'Smartphone')
    for smartphone in Smartphone.objects.all():
        new_price = len(smartphone.brand) * 120
        smartphone.price = new_price
        smartphone.save()


def set_new_category(apps, schema_editor):
    Smartphone = apps.get_model('your_app_name', 'Smartphone')
    for smartphone in Smartphone.objects.all():
        if smartphone.price >= 750:
            smartphone.category = 'Expensive'
        else:
            smartphone.category = 'Cheap'
        smartphone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.CharField(default='empty', max_length=20)),
            ],
        ),
        migrations.RunPython(set_new_price),
        migrations.RunPython(set_new_category),
    ]
