# Generated by Django 4.2.4 on 2023-10-22 16:28
from datetime import timedelta

from django.db import migrations, models


def update_delivery_and_warranty(apps, schema_editor):
    Order = apps.get_model('main_app', 'Order')
    for order in Order.objects.all():
        if order.status == 'Pending':
            order.delivery = order.order_date + timedelta(days=3)
            


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_smartphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('customer_name', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=30)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('warranty', models.CharField(default='No warranty')),
                ('delivery', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RunPython(update_delivery_and_warranty),
    ]
