# Generated by Django 4.2.4 on 2023-10-20 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='is_favourite',
            new_name='is_favorite',
        ),
    ]
