# Generated by Django 4.2.4 on 2023-10-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_hotelroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelroom',
            old_name='room_Type',
            new_name='room_type',
        ),
    ]
